version: '3.3'

services:
  postgres:
    container_name: shopping-db
    image: postgres:15.2
    restart: on-failure
    environment:
      - POSTGRES_DB=shopping
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/shopping-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  shopping:
    container_name: shopping
    image: shopping-dev:latest
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: CompileDaemon --build="go build -o /bin/shopping-server ./cmd/server/" --command=shopping-server -log-prefix=false
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - config/.env

  test:
    container_name: shopping-test
    image: shopping-test:latest
    build:
      context: .
      dockerfile: test.Dockerfile
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    environment:
      TEST_COVERAGE_THRESHOLD: 90
    env_file:
      - config/.env.test
