secretkey: "TOP_SECRET"
database:
  name: "shopping"
  username: "postgres"
  password: "123456"
  host: "localhost"
  port: "5432"
server:
  host: "127.0.0.1"
  port: "8080"
  timeout: 10
storage:
  mediadir: "media"