SecretKey: "TOP_SECRET"
Database:
  Name: "shopping"
  Username: "postgres"
  Password: "123456"
  Host: "localhost"
  Port: "5432"
Server:
  Domain: "http://localhost:8080"
  Port: "8080"
  Timeout: 10
  MediaUrl: "media"
Storage:
  MediaDir: "media"