// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/ismailbayram/shopping/internal/products/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// All provides a mock function with given fields:
func (_m *CategoryRepository) All() ([]domain.Category, error) {
	ret := _m.Called()

	var r0 []domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: _a0
func (_m *CategoryRepository) Create(_a0 domain.Category) (domain.Category, error) {
	ret := _m.Called(_a0)

	var r0 domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Category) (domain.Category, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.Category) domain.Category); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Category)
	}

	if rf, ok := ret.Get(1).(func(domain.Category) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: _a0
func (_m *CategoryRepository) GetByID(_a0 uint) (domain.Category, error) {
	ret := _m.Called(_a0)

	var r0 domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (domain.Category, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) domain.Category); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Category)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *CategoryRepository) Update(_a0 domain.Category) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Category) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCategoryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryRepository(t mockConstructorTestingTNewCategoryRepository) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
